### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wodim** [wodim/pipebot#1]
TODO for pipebot:

- [ ] method to get quoted message and/or arguments, primary/secondary text:
* if quoting, primary is quoted message, secondary is arguments 
* if not quoting, primary is arguments, secondary is nil

- [ ] method to download stuff from message
* if quoting, download quoted file; if nil, download attached file; else nil
* if not quoting, download attached file; else nil

- [ ] k/v db system - in another thread? in jobqueue with rollback? sqlite with json is nice to store raw message data. maybe...

    id (text) | int | text | json | blob

- [ ] method to reply that can back off, reply even when replied to message was deleted, etc
- [ ] better queues: actions (with timeouts), edits, post messages...
- [ ] abstract method to deal with huggingface
- [ ] aliases
- [ ] translate-ng and temp files go in their own folders
- [ ] since config will be moved to the db, translate-ng won't be able to take config from an ini file and args will have to be used instead
- [ ] add magicprompt
- [ ] add deezer lyrics
- [ ] per-group limits:
* automatic greeting when invited: hello, I am not allowed to do anything in this group, contact my owner, etc
* banlist: ignored groups; groups that are left immediately after getting invited
- [ ] https://t.me/c/1074382728/509519
- [ ] faceapp

**Comment by wodim** [comment]
Minimum feature set:

- [ ] /translate, /scramble
- [ ] relay with no gc
- [ ] /voice, /distort
- [ ] huggingface
- [ ] /text, /strip
- [ ] /restart, /flush
- [ ] /leave
